d = {"African Safari Tour": ["https://www.consumeraffairs.com/travel/african-safari-tours", ""],
              "CHINA TOURS COMPANIES": ["https://www.consumeraffairs.com/travel/china-tours", ""],
              "RIVER CRUISE LINES": ["https://www.consumeraffairs.com/travel/river-cruises", ""],
              "AMUSEMENT PARKS": ["https://www.consumeraffairs.com/travel/amusement-parks", ""],
              "CRUISE LINES": ["https://www.consumeraffairs.com/travel/cruises.html", ""],
              "HOTEL BRANDS": ["https://www.consumeraffairs.com/travel/hotels.html", ""],
              "TIMESHARES": ["https://www.consumeraffairs.com/travel/timeshares.html", ""],
              "TRAVEL SITES": ["https://www.consumeraffairs.com/travel/travel-sites", ""],
              "TICKET WEBSITES": ["https://www.consumeraffairs.com/entertainment/ticket-websites", ""],
              "TRAVEL AGENCIES": ["https://www.consumeraffairs.com/travel/agencies.html", ""],
              "LUGGAGE": ["https://www.consumeraffairs.com/shopping/luggage", ""],
              "Travel Insurance": ["https://www.consumeraffairs.com/insurance/travel-insurance", ""],
              "AIRLINES": ["https://www.consumeraffairs.com/travel/airlines.html", ""],
              "TRANSPORTATION AND RIDESHARE APPS": ["https://www.consumeraffairs.com/travel/bus.html", ""],
              "Rental Cars": ["https://www.consumeraffairs.com/travel/car_rental.html", ""],
              "CLOTHING SUBSCRIPTION BOXES": ["https://www.consumeraffairs.com/online/clothing-subscription-box", ""],
              "JEWELRY STORES": ["https://www.consumeraffairs.com/jewelry", ""],
              "JEWELRY INSURANCE": ["https://www.consumeraffairs.com/insurance/jewelry-insurance", ""],
              "RETAIL STORES AND SHOPPING": ["https://www.consumeraffairs.com/retail/national_chains.htm", ""],
              "ACNE TREATMENT": ["https://www.consumeraffairs.com/health/acne-treatment", ""],
              "BEAUTY BOX": ["https://www.consumeraffairs.com/online/beauty-box", ""],
              "MAKEUP BRANDS": ["https://www.consumeraffairs.com/cosmetics/cosmetics.htm", ""],
              "ORGANIC SKIN CARE": ["https://www.consumeraffairs.com/health/organic-skin-care", ""],
              "PERSONAL CARE PRODUCTS": ["https://www.consumeraffairs.com/shopping/personal-care-products", ""],
              "WIGS": ["https://www.consumeraffairs.com/wigs", ""],
              "BACON BRANDS": ["https://www.consumeraffairs.com/food/bacon", ""],
              "CHAIN RESTAURANTS": ["https://www.consumeraffairs.com/food/chain-restaurants", ""],
              "FOOD PRODUCTS": ["https://www.consumeraffairs.com/food", ""],
              "GROCERY STORES": ["https://www.consumeraffairs.com/supermarkets", ""],
              "MEAL DELIVERY SERVICE": ["https://www.consumeraffairs.com/food/meal-delivery-service", ""],
              "WATER DELIVERY SERVICES": ["https://www.consumeraffairs.com/water-delivery-services", ""],
              "GOLF CLUB BRANDS": ["https://www.consumeraffairs.com/retail/golf-club-brands", ""],
              "SPORTING GOODS STORES": ["https://www.consumeraffairs.com/sporting-goods", ""],
              "DENTAL INSURANCE": ["https://www.consumeraffairs.com/insurance/dental-insurance/", ""],
              "DISABILITY INSURANCE": ["https://www.consumeraffairs.com/insurance/dis.html", ""],
              "HEALTH INSURANCE": ["https://www.consumeraffairs.com/insurance/health.html", ""],
              "LIFE INSURANCE COMPANIES": ["https://www.consumeraffairs.com/insurance/life.html", ""],
              "LONG TERM CARE INSURANCE": ["https://www.consumeraffairs.com/insurance/ltc.html", ""],
              "MEDICARE SUPPLEMENTAL INSURANCE": ["https://www.consumeraffairs.com/insurance/medicare-supplemental-insurance/", ""],
              "TRAVEL INSURANCE": ["https://www.consumeraffairs.com/insurance/travel-insurance/", ""],
              "VISION INSURANCE": ["https://www.consumeraffairs.com/insurance/vision-insurance/", ""],
              "FLOOD INSURANCE": ["https://www.consumeraffairs.com/insurance/flood-insurance/", ""],
              "HOMEOWNERS INSURANCE": ["https://www.consumeraffairs.com/insurance/home.html", ""],
              "JEWELRY INSURANCE": ["https://www.consumeraffairs.com/insurance/jewelry-insurance", ""],
              "PET INSURANCE": ["https://www.consumeraffairs.com/pets/pet-insurance", ""],
              "RENTERS INSURANCE": ["https://www.consumeraffairs.com/insurance/renters-insurance", ""],
              "BOAT INSURANCE": ["https://www.consumeraffairs.com/insurance/boat-insurance", ""],
              "CAR INSURANCE": ["https://www.consumeraffairs.com/insurance/car.html", ""],
              "MOTORCYCLE INSURANCE": ["https://www.consumeraffairs.com/insurance/motorcycle-insurance", ""],
              "RV INSURANCE": ["https://www.consumeraffairs.com/insurance/rv-insurance", ""],
              "BANKS AND CREDIT UNIONS": ["https://www.consumeraffairs.com/finance/banks.html", ""],
              "CREDIT CARDS": ["https://www.consumeraffairs.com/credit_cards/credit_cards.html", ""],
              "CREDIT REPORT SITES": ["https://www.consumeraffairs.com/online/credit-report/", ""],
              "MONEY TRANSFER": ["https://www.consumeraffairs.com/finance/money-transfer/", ""],
              "ONLINE BANKS": ["https://www.consumeraffairs.com/finance/online-banks/", ""],
              "PREPAID DEBIT CARDS": ["https://www.consumeraffairs.com/finance/prepaid-debit-cards/", ""],
              "SECURED CREDIT CARDS": ["https://www.consumeraffairs.com/finance/credit-cards/secured/", ""],
              "BILL NEGOTIATION SERVICES": ["https://www.consumeraffairs.com/finance/bill-negotiation/", ""],
              "CREDIT COUNSELING": ["https://www.consumeraffairs.com/finance/credit-counseling/", ""],
              "CREDIT REPAIR COMPANIES": ["https://www.consumeraffairs.com/finance/credit-repair/", ""],
              "DEBT CONSOLIDATION LOAN COMPANIES": ["https://www.consumeraffairs.com/debt_counsel/", ""],
              "DEBT SETTLEMENT": ["https://www.consumeraffairs.com/finance/debt-settlement/", ""],
              "PRE-SETTLEMENT FUNDING": ["https://www.consumeraffairs.com/finance/pre-settlement-funding/", ""],
              "STRUCTURED SETTLEMENT": ["https://www.consumeraffairs.com/finance/structured-settlement/", ""],
              "STUDENT LOAN REFINANCING": ["https://www.consumeraffairs.com/finance/student-loan-consolidation/", ""],
              "TAX RELIEF": ["https://www.consumeraffairs.com/finance/tax-relief/", ""],
              "ANNUITIES": ["https://www.consumeraffairs.com/finance/annuities.html", ""],
              "AUTOMATED INVESTMENT SERVICES": ["https://www.consumeraffairs.com/automated-investment-services/", ""],
              "BITCOIN IRA": ["https://www.consumeraffairs.com/finance/bitcoin-ira/", ""],
              "CROWDFUNDING SITES": ["https://www.consumeraffairs.com/business/crowdfunding-sites/", ""],
              "GOLD DEALERS": ["https://www.consumeraffairs.com/finance/gold-dealers/", ""],
              "GOLD IRA COMPANIES": ["https://www.consumeraffairs.com/finance/gold-ira/", ""],
              "INVESTMENT COMPANIES": ["https://www.consumeraffairs.com/finance/invest.html", ""],
              "LIFE INSURANCE COMPANIES": ["https://www.consumeraffairs.com/insurance/life.html", ""],
              "MUTUAL FUND COMPANIES": ["https://www.consumeraffairs.com/finance/mutual-fund-companies/", ""],
              "ONLINE BROKERS": ["https://www.consumeraffairs.com/finance/online-brokers/", ""],
              "ONLINE FINANCIAL ADVISORS": ["https://www.consumeraffairs.com/finance/financial-planning/", ""],
              "AUTO LOANS": ["https://www.consumeraffairs.com/finance/auto-loans/", ""],
              "BUSINESS LOANS": ["https://www.consumeraffairs.com/business-loans-and-financing/", ""],
              "LOAN COMPANIES": ["https://www.consumeraffairs.com/finance/loan_companies.html", ""],
              "LOAN MODIFICATION COMPANIES": ["https://www.consumeraffairs.com/finance/loan-modification/", ""],
              "PAYDAY AND TITLE LOANS": ["https://www.consumeraffairs.com/finance/payday.html", ""],
              "PERSONAL LOANS": ["https://www.consumeraffairs.com/finance/personal-loans/", ""],
              "SOLAR FINANCING": ["https://www.consumeraffairs.com/finance/solar-financing/", ""],
              "STUDENT LOANS": ["https://www.consumeraffairs.com/finance/student_loans.html", ""],
              "FHA LOAN LENDERS": ["https://www.consumeraffairs.com/finance/fha-loans/", ""],
              "HOME EQUITY LOANS": ["https://www.consumeraffairs.com/finance/home-equity-loans/", ""],
              "JUMBO LOAN LENDERS": ["https://www.consumeraffairs.com/finance/jumbo-loans/", ""],
              "MORTGAGE LENDERS": ["https://www.consumeraffairs.com/finance/finance__companies.html", ""],
              "REVERSE MORTGAGE LENDERS": ["https://www.consumeraffairs.com/reverse-mortgages/", ""],
              "USDA LENDERS": ["https://www.consumeraffairs.com/finance/usda-loans/", ""],
              "VA LOAN LENDERS": ["https://www.consumeraffairs.com/finance/va-loans/", ""],
              "BACKGROUND CHECK COMPANIES": ["https://www.consumeraffairs.com/online/background-check/", ""],
              "IDENTITY THEFT PROTECTION": ["https://www.consumeraffairs.com/privacy/", ""],
              "TAX SOFTWARE AND SERVICES": ["https://www.consumeraffairs.com/finance/tax_prep.html", ""]
              }
